name: autobotx
description: A Flutter app with webview.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7  # Versi ini cocok untuk Flutter 3.x

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
