name: namaproject
description: Deskripsi project kamu

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # dependencies lain...

dev_dependencies:
  flutter_test:
    sdk: flutter
  # dev dependencies lain...

flutter:
  uses-material-design: true
